# Generated by Django 3.2.3 on 2021-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_alter_outlet_outlet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_image',
            field=models.ImageField(blank=True, upload_to='path_and_rename'),
        ),
    ]
