# Generated by Django 3.2.3 on 2021-05-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_section', '0001_initial'),
        ('extra_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.PositiveIntegerField(choices=[(1, 'VEG'), (2, 'NON_VEG')])),
                ('dish_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_extra_item', to='extra_item.extra_item')),
                ('extra_item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_extra_item', to='extra_item.extra_item')),
                ('food_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_section.food_section')),
            ],
        ),
    ]
