# Generated by Django 3.2.3 on 2021-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
