# Generated by Django 3.2.3 on 2021-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210528_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order_detail',
            name='extra_item_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_order_detail',
            name='extra_item_2',
            field=models.BooleanField(default=False),
        ),
    ]
