# Generated by Django 3.2.4 on 2021-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210529_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order_detail',
            name='order_delivery_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery_address',
            field=models.CharField(max_length=500),
        ),
    ]
