# Generated by Django 3.2.3 on 2021-06-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_alter_outlet_outlet_image'),
        ('orders', '0005_order_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlet.outlet'),
            preserve_default=False,
        ),
    ]
